# Generated by Django 3.1.2 on 2020-10-19 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="equipment_id",
                        default=uuid.UUID("1134982c-8a16-402d-8d5a-2e7ca18ecb58"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="equipment_name", max_length=250)),
            ],
            options={
                "db_table": "equipment",
            },
        ),
        migrations.CreateModel(
            name="EquipmentMake",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="equipment_make_id",
                        default=uuid.UUID("862ffd3e-dca5-46ee-a39b-9d82f88d802c"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(db_column="equipment_make_name", max_length=250),
                ),
            ],
            options={
                "db_table": "equipment_make",
            },
        ),
        migrations.CreateModel(
            name="EquipmentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="equipment_make_model_id",
                        default=uuid.UUID("f4d56b34-5fb1-463f-b780-9cfc77e61ccc"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(db_column="equipment_model_name", max_length=750),
                ),
            ],
            options={
                "db_table": "equipment_make_model",
            },
        ),
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="equipment_type_id",
                        default=uuid.UUID("8a6294dc-1a1f-469a-9c9f-f2320ba7877f"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="equipment_type_name", max_length=250, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "equipment_type",
            },
        ),
        migrations.CreateModel(
            name="EquipmentUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="equipment_user_rel_id",
                        default=uuid.UUID("781ee9de-9003-4565-8964-f83d54a7d724"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "db_table": "equipment_user_rel",
            },
        ),
    ]
