# Generated by Django 3.1.2 on 2020-10-19 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipment", "0001_initial"),
        ("farm", "0002_plan_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="equipmentmodel",
            name="equipment_type",
            field=models.ForeignKey(
                db_column="equipment_type_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.equipmenttype",
            ),
        ),
        migrations.AddField(
            model_name="equipmentmodel",
            name="make",
            field=models.ForeignKey(
                db_column="equipment_make_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.equipmentmake",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="farm",
            field=models.ForeignKey(
                db_column="organization_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="farm.farm",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="make_model",
            field=models.ForeignKey(
                db_column="equipment_make_model_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.equipmentmodel",
            ),
        ),
    ]
