# Generated by Django 3.1.2 on 2020-10-19 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackgroundImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="background_image_id",
                        default=uuid.UUID("6e7d33bb-5ba1-4dd9-9fa0-90ca248dd7e7"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(db_column="image_description", null=True),
                ),
                (
                    "filename",
                    models.CharField(db_column="image_filename", max_length=750),
                ),
                ("image_approved", models.BooleanField(default=False)),
                ("image_for_day", models.IntegerField(null=True)),
                ("image_previously_used", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "background_image",
            },
        ),
    ]
