# Generated by Django 3.1.2 on 2020-10-19 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("field", "0001_initial"),
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryUnitOfMeasure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="inventory_uom_type_id",
                        default=uuid.UUID("27e11571-ba4c-4aa9-9bdb-ed4fa8ccf545"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="uom_type_name", max_length=250)),
            ],
            options={
                "db_table": "inventory_uom_type",
            },
        ),
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="shopping_list_id",
                        default=uuid.UUID("f0862bf7-deb8-4ef3-b22f-a64d45dc82ab"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item",
                    models.CharField(db_column="shopping_list_item", max_length=750),
                ),
                ("quantity", models.FloatField(db_column="shopping_list_quantity")),
                (
                    "farm_id",
                    models.ForeignKey(
                        db_column="organization_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farm.farm",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="field.location",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.ForeignKey(
                        db_column="shopping_list_uom",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventoryunitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "shopping_list",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="inventory_id",
                        default=uuid.UUID("6dfb7d68-15a1-494d-837a-4925db0f2594"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("item", models.CharField(db_column="inventory_item", max_length=750)),
                ("quantity", models.FloatField(db_column="inventory_quantity")),
                (
                    "farm_id",
                    models.ForeignKey(
                        db_column="organization_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farm.farm",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="field.location",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.ForeignKey(
                        db_column="inventory_uom",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventoryunitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "inventory",
            },
        ),
    ]
