# Generated by Django 3.1.2 on 2020-10-19 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farm", "0002_plan_location"),
        ("field", "0002_auto_20201019_1659"),
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="planner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="organizationtypelocationtyperel",
            name="farm_type",
            field=models.ForeignKey(
                db_column="organization_type_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="farm.organizationtype",
            ),
        ),
        migrations.AddField(
            model_name="organizationtypelocationtyperel",
            name="location_type",
            field=models.ForeignKey(
                db_column="location_type_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="field.locationtype",
            ),
        ),
        migrations.AddField(
            model_name="organizationtypeactivityrel",
            name="activity_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="task.activity"
            ),
        ),
        migrations.AddField(
            model_name="organizationtypeactivityrel",
            name="org_type",
            field=models.ForeignKey(
                db_column="organization_type_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="farm.organizationtype",
            ),
        ),
        migrations.AddField(
            model_name="organizationlocationrel",
            name="farm",
            field=models.ForeignKey(
                db_column="organization_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="farm.farm",
            ),
        ),
        migrations.AddField(
            model_name="organizationlocationrel",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="field.location"
            ),
        ),
        migrations.AddField(
            model_name="farmusers",
            name="farm",
            field=models.ForeignKey(
                db_column="organization_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="farm.farm",
            ),
        ),
        migrations.AddField(
            model_name="farmusers",
            name="role",
            field=models.ForeignKey(
                db_column="organization_role_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="farm.organizationrole",
            ),
        ),
        migrations.AddField(
            model_name="farmusers",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farmtype",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="farm.farm"
            ),
        ),
        migrations.AddField(
            model_name="farmtype",
            name="organization_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="farm.organizationtype"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="type",
            field=models.ForeignKey(
                db_column="organization_type_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="farm.organizationtype",
            ),
        ),
    ]
