# Generated by Django 3.1.2 on 2020-10-19 16:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("field", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="activity_type_id",
                        default=uuid.UUID("26775ab7-2d14-4b78-8cbc-0874786eb76d"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="activity_type_name", max_length=250, unique=True
                    ),
                ),
                ("requires_crop", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField()),
            ],
            options={
                "db_table": "activity_type",
            },
        ),
        migrations.CreateModel(
            name="ActivityDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="activity_detail_id",
                        default=uuid.UUID("a5001866-6799-4bbc-a83a-91a2cb1c7ea5"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="activity_detail_name", max_length=250, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "activity_detail",
            },
        ),
        migrations.CreateModel(
            name="ActivityDetailRel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="activity_type_detail_rel_id",
                        default=uuid.UUID("beef7a07-bae6-43e9-97dd-65116bbece38"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sort_order", models.IntegerField()),
            ],
            options={
                "db_table": "activity_type_detail_rel",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="message_id",
                        default=uuid.UUID("2cec89f6-ec2c-4d1f-8a85-c6e64e366ac7"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message_year", models.IntegerField()),
                ("is_archived", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("message", models.TextField()),
                (
                    "message_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("message_image", models.CharField(max_length=750, null=True)),
            ],
            options={
                "db_table": "task_message",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="task_id",
                        default=uuid.UUID("8974d27d-5046-43da-afb2-5a62e1ef8e3b"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_start_date", models.DateTimeField()),
                ("task_end_date", models.DateTimeField()),
                ("task_notes", models.TextField()),
                ("task_amount", models.FloatField(null=True)),
                (
                    "task_verification_image",
                    models.CharField(max_length=750, null=True),
                ),
                ("is_draft", models.BooleanField(default=False)),
                ("task_available_date", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "task",
            },
        ),
        migrations.CreateModel(
            name="TaskDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="task_detail_id",
                        default=uuid.UUID("5f098696-ea8b-4422-a1ff-d2d92e5ca1a8"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "detail_value",
                    models.CharField(db_column="activity_detail_value", max_length=250),
                ),
            ],
            options={
                "db_table": "task_details",
            },
        ),
        migrations.CreateModel(
            name="TaskEquipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="task_equipment_id",
                        default=uuid.UUID("b327142d-53f2-43c7-bd73-9779e5f43130"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "task_equipment",
            },
        ),
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="task_history_id",
                        default=uuid.UUID("ed5a995a-bf81-407e-bf28-0f4c53ef4159"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status_date_change", models.DateTimeField()),
                (
                    "status_change_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
            ],
            options={
                "db_table": "task_history",
            },
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="task_status_type_id",
                        default=uuid.UUID("129f88e3-b290-44aa-a151-d5370feafa98"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="task_status_name", max_length=75)),
            ],
            options={
                "db_table": "task_status_type",
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="work_order_id",
                        default=uuid.UUID("af8005b1-b31b-4149-ab2c-6eef34c6e60f"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="task.activity"
                    ),
                ),
            ],
            options={
                "db_table": "work_order",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="work_order_location_rel_id",
                        default=uuid.UUID("b5eff93f-ccc1-489b-a0b8-6159a0c853ce"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="field.location"
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="task.workorder"
                    ),
                ),
            ],
            options={
                "db_table": "work_order_location_rel",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderActivityDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="work_order_activity_detail_rel_id",
                        default=uuid.UUID("549fd09f-6e68-4dcf-b983-10684e45f88f"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("detail_value", models.CharField(max_length=75)),
                (
                    "activity_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task.activitydetail",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="task.workorder"
                    ),
                ),
            ],
            options={
                "db_table": "work_order_activity_detail_rel",
            },
        ),
    ]
