# Generated by Django 3.1.2 on 2020-10-19 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farm", "0003_auto_20201019_1659"),
        ("crop", "0001_initial"),
        ("equipment", "0002_auto_20201019_1659"),
        ("field", "0002_auto_20201019_1659"),
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="creator_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="taskhistory",
            name="task_status",
            field=models.ForeignKey(
                db_column="task_status_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="task.taskstatus",
            ),
        ),
        migrations.AddField(
            model_name="taskhistory",
            name="update_user",
            field=models.ForeignKey(
                db_column="user_update_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskequipment",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_equipment",
                to="equipment.equipment",
            ),
        ),
        migrations.AddField(
            model_name="taskequipment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_task",
                to="task.task",
            ),
        ),
        migrations.AddField(
            model_name="taskdetails",
            name="activity_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="task.activitydetail"
            ),
        ),
        migrations.AddField(
            model_name="taskdetails",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="task.task"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_activity",
            field=models.ForeignKey(
                db_column="task_activity_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="task.activity",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_assignee",
            field=models.ForeignKey(
                db_column="task_assignee_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_assignee_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_creator",
            field=models.ForeignKey(
                db_column="task_creator_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_creator_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_crop",
            field=models.ForeignKey(
                db_column="task_crop_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="crop.crop",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_location",
            field=models.ForeignKey(
                db_column="task_location_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="field.location",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_status",
            field=models.ForeignKey(
                db_column="task_status_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="task.taskstatus",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="farm",
            field=models.ForeignKey(
                db_column="organization_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="farm.farm",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                db_column="message_recipient",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_recipient_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                db_column="message_sender",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_sender_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="task",
            field=models.ForeignKey(
                db_column="task_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="task.task",
            ),
        ),
        migrations.AddField(
            model_name="activitydetailrel",
            name="activity",
            field=models.ForeignKey(
                db_column="activity_type_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="task.activity",
            ),
        ),
        migrations.AddField(
            model_name="activitydetailrel",
            name="activity_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="task.activitydetail"
            ),
        ),
    ]
