# Generated by Django 3.1.2 on 2020-10-19 16:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="location_id",
                        default=uuid.UUID("8be94cf6-a4da-4071-8b5d-62949c2683bd"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="location_name", max_length=750)),
                ("acres", models.FloatField()),
                ("image", models.CharField(db_column="location_image", max_length=750)),
                (
                    "geo_center",
                    django.contrib.gis.db.models.fields.PointField(
                        db_column="location_geo_center", srid=4326
                    ),
                ),
                (
                    "drawn_area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        db_column="location_drawn_area", srid=4326
                    ),
                ),
                ("legal_name", models.CharField(blank=True, max_length=750, null=True)),
            ],
            options={
                "db_table": "location",
            },
        ),
        migrations.CreateModel(
            name="LocationType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="location_type_id",
                        default=uuid.UUID("4a10ac29-1a6b-4663-975b-3fa8bc7efb44"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="location_type_name", max_length=250, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "location_type",
            },
        ),
        migrations.CreateModel(
            name="LocationTypeActivityType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="location_type_activity_type_rel_id",
                        default=uuid.UUID("be1c65c4-0a1d-4c01-949f-94cc10d8ea44"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "location_type_activity_type_rel",
            },
        ),
    ]
