# Generated by Django 3.1.2 on 2020-10-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("field", "0001_initial"),
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationtypeactivitytype",
            name="activity_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="task.activity"
            ),
        ),
        migrations.AddField(
            model_name="locationtypeactivitytype",
            name="location_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="field.locationtype"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="type",
            field=models.ForeignKey(
                db_column="location_type_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="field.locationtype",
            ),
        ),
    ]
